### ISSUE TITLE
编译失败，需要认证了

### ISSUE THREAD

**Issue by AnonymHK** [Vpay-Collection/vpay-android#2]
Could not GET 'https://jitpack.io/com/gitee/zackratos/UltimateBarX/dev-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized

突然需要认证了？

**Comment by dreamncn** [comment]
我觉得是服务短暂性出现了问题：https://github.com/jitpack/jitpack.io/issues/4039

**Comment by ID31500** [comment]
Hey any update on the solution Yet? or any Alernative to this

**Comment by AnkioTomas** [comment]
> Hey any update on the solution Yet? or any Alernative to this

Just wait for service to resume
